name: 04 - Using Actions
on: push
# workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Printing Folder
      #   run: |
      #     echo "Displaying the project folder structure:"
      #     ls -R
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: |
          cd ./04-using-actions
          npm ci
      - name: Run Unit Tests
        run: |
          cd ./04-using-actions
          npm run test
